//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


namespace OggDudeData.Model.Character
{
   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class Requirement {
    
      private string wearingArmorField;
    
      private string careerField;
    
      private string specializationField;
    
      private string nonCareerField;
    
      private string soakAtLeastField;
    
      private string wieldingMeleeField;
    
      private string wieldingBrawlField;
    
      private string wieldingLightsaberField;
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public string WearingArmor {
         get {
            return this.wearingArmorField;
         }
         set {
            this.wearingArmorField = value;
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public string Career {
         get {
            return this.careerField;
         }
         set {
            this.careerField = value;
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public string Specialization {
         get {
            return this.specializationField;
         }
         set {
            this.specializationField = value;
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public string NonCareer {
         get {
            return this.nonCareerField;
         }
         set {
            this.nonCareerField = value;
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public string SoakAtLeast {
         get {
            return this.soakAtLeastField;
         }
         set {
            this.soakAtLeastField = value;
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public string WieldingMelee {
         get {
            return this.wieldingMeleeField;
         }
         set {
            this.wieldingMeleeField = value;
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public string WieldingBrawl {
         get {
            return this.wieldingBrawlField;
         }
         set {
            this.wieldingBrawlField = value;
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public string WieldingLightsaber {
         get {
            return this.wieldingLightsaberField;
         }
         set {
            this.wieldingLightsaberField = value;
         }
      }
   }
}