//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SessionManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ability {
            get {
                object obj = ResourceManager.GetObject("Ability", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility.
        /// </summary>
        public static string Ag {
            get {
                return ResourceManager.GetString("Ag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astrogation.
        /// </summary>
        public static string Astrogation {
            get {
                return ResourceManager.GetString("Astrogation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletics.
        /// </summary>
        public static string Athletics {
            get {
                return ResourceManager.GetString("Athletics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brawn.
        /// </summary>
        public static string Br {
            get {
                return ResourceManager.GetString("Br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brawl.
        /// </summary>
        public static string Brawl {
            get {
                return ResourceManager.GetString("Brawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Name.
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristics.
        /// </summary>
        public static string Characteristics {
            get {
                return ResourceManager.GetString("Characteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charm.
        /// </summary>
        public static string Charm {
            get {
                return ResourceManager.GetString("Charm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coercion.
        /// </summary>
        public static string Coercion {
            get {
                return ResourceManager.GetString("Coercion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Skills.
        /// </summary>
        public static string Combat {
            get {
                return ResourceManager.GetString("Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers.
        /// </summary>
        public static string Computers {
            get {
                return ResourceManager.GetString("Computers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool.
        /// </summary>
        public static string Cool {
            get {
                return ResourceManager.GetString("Cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordination.
        /// </summary>
        public static string Coordination {
            get {
                return ResourceManager.GetString("Coordination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Worlds.
        /// </summary>
        public static string CoreWorlds {
            get {
                return ResourceManager.GetString("CoreWorlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cunning.
        /// </summary>
        public static string Cun {
            get {
                return ResourceManager.GetString("Cun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deception.
        /// </summary>
        public static string Deception {
            get {
                return ResourceManager.GetString("Deception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string Defense {
            get {
                return ResourceManager.GetString("Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice.
        /// </summary>
        public static string Dice {
            get {
                return ResourceManager.GetString("Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice Pool.
        /// </summary>
        public static string DicePool {
            get {
                return ResourceManager.GetString("DicePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        public static string Discipline {
            get {
                return ResourceManager.GetString("Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Skills.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunnery.
        /// </summary>
        public static string Gunnery {
            get {
                return ResourceManager.GetString("Gunnery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        public static string Heavy {
            get {
                return ResourceManager.GetString("Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injuries.
        /// </summary>
        public static string Injuries {
            get {
                return ResourceManager.GetString("Injuries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellect.
        /// </summary>
        public static string Int {
            get {
                return ResourceManager.GetString("Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Skills.
        /// </summary>
        public static string Knowledge {
            get {
                return ResourceManager.GetString("Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadership.
        /// </summary>
        public static string Leadership {
            get {
                return ResourceManager.GetString("Leadership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightsaber.
        /// </summary>
        public static string Lightsaber {
            get {
                return ResourceManager.GetString("Lightsaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lore.
        /// </summary>
        public static string Lore {
            get {
                return ResourceManager.GetString("Lore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanics.
        /// </summary>
        public static string Mechanics {
            get {
                return ResourceManager.GetString("Mechanics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        public static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string Melee {
            get {
                return ResourceManager.GetString("Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiation.
        /// </summary>
        public static string Negotiation {
            get {
                return ResourceManager.GetString("Negotiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Rim.
        /// </summary>
        public static string OuterRim {
            get {
                return ResourceManager.GetString("OuterRim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perception.
        /// </summary>
        public static string Perception {
            get {
                return ResourceManager.GetString("Perception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piloting.
        /// </summary>
        public static string Piloting {
            get {
                return ResourceManager.GetString("Piloting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planetary.
        /// </summary>
        public static string Planetary {
            get {
                return ResourceManager.GetString("Planetary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence.
        /// </summary>
        public static string Pr {
            get {
                return ResourceManager.GetString("Pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Proficiency {
            get {
                object obj = ResourceManager.GetObject("Proficiency", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string Ranged {
            get {
                return ResourceManager.GetString("Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilience.
        /// </summary>
        public static string Resilience {
            get {
                return ResourceManager.GetString("Resilience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skulduggery.
        /// </summary>
        public static string Skulduggery {
            get {
                return ResourceManager.GetString("Skulduggery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soak.
        /// </summary>
        public static string Soak {
            get {
                return ResourceManager.GetString("Soak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specializations.
        /// </summary>
        public static string Specializations {
            get {
                return ResourceManager.GetString("Specializations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string Species {
            get {
                return ResourceManager.GetString("Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stealth.
        /// </summary>
        public static string Stealth {
            get {
                return ResourceManager.GetString("Stealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strain.
        /// </summary>
        public static string Strain {
            get {
                return ResourceManager.GetString("Strain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streetwise.
        /// </summary>
        public static string Streetwise {
            get {
                return ResourceManager.GetString("Streetwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival.
        /// </summary>
        public static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        public static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underworld.
        /// </summary>
        public static string Underworld {
            get {
                return ResourceManager.GetString("Underworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigilance.
        /// </summary>
        public static string Vigilance {
            get {
                return ResourceManager.GetString("Vigilance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warfare.
        /// </summary>
        public static string Warfare {
            get {
                return ResourceManager.GetString("Warfare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willpower.
        /// </summary>
        public static string Wil {
            get {
                return ResourceManager.GetString("Wil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wounds.
        /// </summary>
        public static string Wounds {
            get {
                return ResourceManager.GetString("Wounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenology.
        /// </summary>
        public static string Xenology {
            get {
                return ResourceManager.GetString("Xenology", resourceCulture);
            }
        }
    }
}
