//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace OggDudeData.Model
{
   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
   [System.Serializable()]
   [System.Diagnostics.DebuggerStepThrough()]
   [System.ComponentModel.DesignerCategory("code")]
   [XmlType(AnonymousType = true)]
   [XmlRoot(Namespace = "", IsNullable = false)]
   public partial class Characteristics
   {

      private CharacteristicsCharacteristic[] characteristicField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Characteristic")]
      public CharacteristicsCharacteristic[] Characteristic
      {
         get { return this.characteristicField; }
         set { this.characteristicField = value; }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
   [System.Serializable()]
   [System.Diagnostics.DebuggerStepThrough()]
   [System.ComponentModel.DesignerCategory("code")]
   [XmlType(AnonymousType = true)]
   public partial class CharacteristicsCharacteristic
   {

      private string keyField;

      private string nameField;

      private string abbrevField;

      private string descriptionField;

      /// <remarks/>
      public string Key
      {
         get { return this.keyField; }
         set { this.keyField = value; }
      }

      /// <remarks/>
      public string Name
      {
         get { return this.nameField; }
         set { this.nameField = value; }
      }

      /// <remarks/>
      public string Abbrev
      {
         get { return this.abbrevField; }
         set { this.abbrevField = value; }
      }

      /// <remarks/>
      public string Description
      {
         get { return this.descriptionField; }
         set { this.descriptionField = value; }
      }
   }
}