//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace OggDudeData.Model
{
   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
   [System.Serializable()]
   [System.Diagnostics.DebuggerStepThrough()]
   [System.ComponentModel.DesignerCategory("code")]
   [XmlType(AnonymousType = true)]
   [XmlRoot(Namespace = "", IsNullable = false)]
   public partial class Skills
   {

      private SkillsSkill[] skillField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Skill")]
      public SkillsSkill[] Skill
      {
         get { return this.skillField; }
         set { this.skillField = value; }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
   [System.Serializable()]
   [System.Diagnostics.DebuggerStepThrough()]
   [System.ComponentModel.DesignerCategory("code")]
   [XmlType(AnonymousType = true)]
   public partial class SkillsSkill
   {

      private string keyField;

      private string nameField;

      private string descriptionField;

      private string sourceField;

      private string charKeyField;

      private string typeValueField;

      /// <remarks/>
      public string Key
      {
         get { return this.keyField; }
         set { this.keyField = value; }
      }

      /// <remarks/>
      public string Name
      {
         get { return this.nameField; }
         set { this.nameField = value; }
      }

      /// <remarks/>
      public string Description
      {
         get { return this.descriptionField; }
         set { this.descriptionField = value; }
      }

      /// <remarks/>
      public string Source
      {
         get { return this.sourceField; }
         set { this.sourceField = value; }
      }

      /// <remarks/>
      public string CharKey
      {
         get { return this.charKeyField; }
         set { this.charKeyField = value; }
      }

      /// <remarks/>
      public string TypeValue
      {
         get { return this.typeValueField; }
         set { this.typeValueField = value; }
      }
   }
}